"""Generate a PDF report from analysis results."""

import io
from xml.sax.saxutils import escape as _xml_escape
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
)


def _esc(text: str) -> str:
    """Escape text for safe use inside ReportLab Paragraph XML."""
    return _xml_escape(str(text)) if text else ""


def _score_color(score: int):
    if score >= 80:
        return colors.HexColor("#16a34a")
    if score >= 60:
        return colors.HexColor("#f59e0b")
    return colors.HexColor("#dc2626")


def generate_report_pdf(result: dict, filename: str = "resume") -> bytes:
    """Generate a styled PDF report and return raw bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("RTitle", parent=styles["Title"], fontSize=22, spaceAfter=4)
    subtitle_style = ParagraphStyle("RSub", parent=styles["Normal"], fontSize=10, textColor=colors.grey)
    heading_style = ParagraphStyle("RH2", parent=styles["Heading2"], fontSize=14, spaceBefore=16, spaceAfter=6)
    body_style = ParagraphStyle("RBody", parent=styles["Normal"], fontSize=10, leading=14)
    bullet_style = ParagraphStyle("RBullet", parent=body_style, leftIndent=18, bulletIndent=6)

    elements = []

    # Header
    elements.append(Paragraph("ResumeIQ Analysis Report", title_style))
    elements.append(Paragraph(f"File: {_esc(filename)}", subtitle_style))
    if result.get("detected_role"):
        elements.append(Paragraph(f"Detected Role: {_esc(result['detected_role'])}", subtitle_style))
    elements.append(Spacer(1, 12))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e5e7eb")))
    elements.append(Spacer(1, 12))

    # Score table
    score_data = [
        ["Metric", "Score"],
        ["ATS Score", f"{result.get('ats_score', 0)}/100"],
        ["Match Score", f"{result.get('match_score', 0)}/100"],
        ["Skills", f"{result.get('skills_score', 0)}/100"],
        ["Keywords", f"{result.get('keyword_score', 0)}/100"],
        ["Experience", f"{result.get('experience_score', 0)}/100"],
        ["Projects", f"{result.get('project_score', 0)}/100"],
    ]
    t = Table(score_data, colWidths=[3.5 * inch, 2 * inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 12))

    # Summary
    if result.get("summary"):
        elements.append(Paragraph("Summary", heading_style))
        elements.append(Paragraph(_esc(result["summary"]), body_style))

    # ATS Explanation
    if result.get("ats_explanation"):
        elements.append(Paragraph("ATS Analysis", heading_style))
        elements.append(Paragraph(_esc(result["ats_explanation"]), body_style))

    # Match Explanation
    if result.get("match_explanation"):
        elements.append(Paragraph("Match Analysis", heading_style))
        elements.append(Paragraph(_esc(result["match_explanation"]), body_style))

    # Keywords
    matched = result.get("matched_keywords", [])
    missing = result.get("missing_keywords", [])
    if matched:
        elements.append(Paragraph("Matched Keywords", heading_style))
        elements.append(Paragraph(_esc(", ".join(str(k) for k in matched)), body_style))
    if missing:
        elements.append(Paragraph("Missing Keywords", heading_style))
        elements.append(Paragraph(_esc(", ".join(str(k) for k in missing)), body_style))

    # Suggestions
    suggestions = result.get("suggestions", [])
    if suggestions:
        elements.append(Paragraph("Suggestions", heading_style))
        for s in suggestions:
            elements.append(Paragraph(f"&bull; {_esc(str(s))}", bullet_style))

    # Weak points
    weak = result.get("weak_points", [])
    if weak:
        elements.append(Paragraph("Weak Points", heading_style))
        for w in weak:
            elements.append(Paragraph(f"&bull; {_esc(str(w))}", bullet_style))

    elements.append(Spacer(1, 24))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#d1d5db")))
    elements.append(Spacer(1, 6))
    elements.append(Paragraph("Generated by ResumeIQ", ParagraphStyle("Footer", parent=body_style, fontSize=8, textColor=colors.grey, alignment=1)))

    doc.build(elements)
    return buf.getvalue()
